#!/bin/bash

declare -A country_map
country_map["afghanistan"]="af"
country_map["aland islands"]="ax"
country_map["albania"]="al"
country_map["algeria"]="dz"
country_map["american samoa"]="as"
country_map["andorra"]="ad"
country_map["angola"]="ao"
country_map["anguilla"]="ai"
country_map["antarctica"]="aq"
country_map["antigua and barbuda"]="ag"
country_map["argentina"]="ar"
country_map["armenia"]="am"
country_map["aruba"]="aw"
country_map["australia"]="au"
country_map["austria"]="at"
country_map["azerbaijan"]="az"
country_map["bahamas"]="bs"
country_map["bahrain"]="bh"
country_map["bangladesh"]="bd"
country_map["barbados"]="bb"
country_map["belarus"]="by"
country_map["belgium"]="be"
country_map["belize"]="bz"
country_map["benin"]="bj"
country_map["bermuda"]="bm"
country_map["bhutan"]="bt"
country_map["bolivia"]="bo"
country_map["bonaire, sint eustatius and saba"]="bq"
country_map["bosnia and herzegovina"]="ba"
country_map["botswana"]="bw"
country_map["bouvet island"]="bv"
country_map["brazil"]="br"
country_map["british indian ocean territory"]="io"
country_map["brunei darussalam"]="bn"
country_map["bulgaria"]="bg"
country_map["burkina faso"]="bf"
country_map["burundi"]="bi"
country_map["cabo verde"]="cv"
country_map["cambodia"]="kh"
country_map["cameroon"]="cm"
country_map["canada"]="ca"
country_map["cayman islands"]="ky"
country_map["central african republic"]="cf"
country_map["chad"]="td"
country_map["chile"]="cl"
country_map["china"]="cn"
country_map["christmas island"]="cx"
country_map["cocos (keeling) islands"]="cc"
country_map["colombia"]="co"
country_map["comoros"]="km"
country_map["congo (the democratic republic of the)"]="cd"
country_map["congo (the)"]="cg"
country_map["cook islands"]="ck"
country_map["costa rica"]="cr"
country_map["cote d'ivoire"]="ci"
country_map["croatia"]="hr"
country_map["cuba"]="cu"
country_map["curacao"]="cw"
country_map["cyprus"]="cy"
country_map["czechia"]="cz"
country_map["denmark"]="dk"
country_map["djibouti"]="dj"
country_map["dominica"]="dm"
country_map["dominican republic"]="do"
country_map["ecuador"]="ec"
country_map["egypt"]="eg"
country_map["el salvador"]="sv"
country_map["equatorial guinea"]="gq"
country_map["eritrea"]="er"
country_map["estonia"]="ee"
country_map["eswatini"]="sz"
country_map["ethiopia"]="et"
country_map["falkland islands (malvinas)"]="fk"
country_map["faroe islands"]="fo"
country_map["fiji"]="fj"
country_map["finland"]="fi"
country_map["france"]="fr"
country_map["french guiana"]="gf"
country_map["french polynesia"]="pf"
country_map["french southern territories"]="tf"
country_map["gabon"]="ga"
country_map["gambia"]="gm"
country_map["georgia"]="ge"
country_map["germany"]="de"
country_map["ghana"]="gh"
country_map["gibraltar"]="gi"
country_map["greece"]="gr"
country_map["greenland"]="gl"
country_map["grenada"]="gd"
country_map["guadeloupe"]="gp"
country_map["guam"]="gu"
country_map["guatemala"]="gt"
country_map["guernsey"]="gg"
country_map["guinea"]="gn"
country_map["guinea-bissau"]="gw"
country_map["guyana"]="gy"
country_map["haiti"]="ht"
country_map["heard island and mcdonald islands"]="hm"
country_map["holy see"]="va"
country_map["honduras"]="hn"
country_map["hong kong"]="hk"
country_map["hungary"]="hu"
country_map["iceland"]="is"
country_map["india"]="in"
country_map["indonesia"]="id"
country_map["iran"]="ir"
country_map["iraq"]="iq"
country_map["ireland"]="ie"
country_map["isle of man"]="im"
country_map["israel"]="il"
country_map["italy"]="it"
country_map["jamaica"]="jm"
country_map["japan"]="jp"
country_map["jersey"]="je"
country_map["jordan"]="jo"
country_map["kazakhstan"]="kz"
country_map["kenya"]="ke"
country_map["kiribati"]="ki"
country_map["korea (the democratic people's republic of)"]="kp"
country_map["korea (the republic of)"]="kr"
country_map["kuwait"]="kw"
country_map["kyrgyzstan"]="kg"
country_map["lao people's democratic republic"]="la"
country_map["latvia"]="lv"
country_map["lebanon"]="lb"
country_map["lesotho"]="ls"
country_map["liberia"]="lr"
country_map["libya"]="ly"
country_map["liechtenstein"]="li"
country_map["lithuania"]="lt"
country_map["luxembourg"]="lu"
country_map["macao"]="mo"
country_map["madagascar"]="mg"
country_map["malawi"]="mw"
country_map["malaysia"]="my"
country_map["maldives"]="mv"
country_map["mali"]="ml"
country_map["malta"]="mt"
country_map["marshall islands"]="mh"
country_map["martinique"]="mq"
country_map["mauritania"]="mr"
country_map["mauritius"]="mu"
country_map["mayotte"]="yt"
country_map["mexico"]="mx"
country_map["micronesia (federated states of)"]="fm"
country_map["moldova (the republic of)"]="md"
country_map["monaco"]="mc"
country_map["mongolia"]="mn"
country_map["montenegro"]="me"
country_map["montserrat"]="ms"
country_map["morocco"]="ma"
country_map["mozambique"]="mz"
country_map["myanmar"]="mm"
country_map["namibia"]="na"
country_map["nauru"]="nr"
country_map["nepal"]="np"
country_map["netherlands"]="nl"
country_map["new caledonia"]="nc"
country_map["new zealand"]="nz"
country_map["nicaragua"]="ni"
country_map["niger"]="ne"
country_map["nigeria"]="ng"
country_map["niue"]="nu"
country_map["norfolk island"]="nf"
country_map["north macedonia"]="mk"
country_map["northern mariana islands"]="mp"
country_map["norway"]="no"
country_map["oman"]="om"
country_map["pakistan"]="pk"
country_map["palau"]="pw"
country_map["palestine, state of"]="ps"
country_map["panama"]="pa"
country_map["papua new guinea"]="pg"
country_map["paraguay"]="py"
country_map["peru"]="pe"
country_map["philippines"]="ph"
country_map["pitcairn"]="pn"
country_map["poland"]="pl"
country_map["portugal"]="pt"
country_map["puerto rico"]="pr"
country_map["qatar"]="qa"
country_map["reunion"]="re"
country_map["romania"]="ro"
country_map["russia"]="ru"
country_map["rwanda"]="rw"
country_map["saint barthelemy"]="bl"
country_map["saint helena, ascension and tristan da cunha"]="sh"
country_map["saint kitts and nevis"]="kn"
country_map["saint lucia"]="lc"
country_map["saint martin (french part)"]="mf"
country_map["saint pierre and miquelon"]="pm"
country_map["saint vincent and the grenadines"]="vc"
country_map["samoa"]="ws"
country_map["san marino"]="sm"
country_map["sao tome and principe"]="st"
country_map["saudi arabia"]="sa"
country_map["senegal"]="sn"
country_map["serbia"]="rs"
country_map["seychelles"]="sc"
country_map["sierra leone"]="sl"
country_map["singapore"]="sg"
country_map["sint maarten (dutch part)"]="sx"
country_map["slovakia"]="sk"
country_map["slovenia"]="si"
country_map["solomon islands"]="sb"
country_map["somalia"]="so"
country_map["south africa"]="za"
country_map["south georgia and the south sandwich islands"]="gs"
country_map["south sudan"]="ss"
country_map["spain"]="es"
country_map["sri lanka"]="lk"
country_map["sudan"]="sd"
country_map["suriname"]="sr"
country_map["svalbard and jan mayen"]="sj"
country_map["sweden"]="se"
country_map["switzerland"]="ch"
country_map["syrian arab republic"]="sy"
country_map["taiwan (province of china)"]="tw"
country_map["tajikistan"]="tj"
country_map["tanzania, united republic of"]="tz"
country_map["thailand"]="th"
country_map["timor-leste"]="tl"
country_map["togo"]="tg"
country_map["tokelau"]="tk"
country_map["tonga"]="to"
country_map["trinidad and tobago"]="tt"
country_map["tunisia"]="tn"
country_map["turkey"]="tr"
country_map["turkmenistan"]="tm"
country_map["turks and caicos islands"]="tc"
country_map["tuvalu"]="tv"
country_map["uganda"]="ug"
country_map["ukraine"]="ua"
country_map["united arab emirates"]="ae"
country_map["united kingdom"]="gb"
country_map["uk"]="gb"
country_map["united states"]="us"
country_map["usa"]="us"
country_map["united states minor outlying islands"]="um"
country_map["uruguay"]="uy"
country_map["uzbekistan"]="uz"
country_map["vanuatu"]="vu"
country_map["venezuela"]="ve"
country_map["viet nam"]="vn"
country_map["virgin islands (british)"]="vg"
country_map["virgin islands (u.s.)"]="vi"
country_map["wallis and futuna"]="wf"
country_map["western sahara"]="eh"
country_map["yemen"]="ye"
country_map["zambia"]="zm"
country_map["zimbabwe"]="zw"

read -p "[$(date '+%Y-%m-%d %H:%M:%S')] [?] Enter the name or code of the country to block: " country_input

if [ -z "$country_input" ]; then
    echo "[$(date '+%Y-%m-%d %H:%M:%S')] [ERROR] No country specified."
    exit 1
fi

INPUT_LOWER=${country_input,,}
if [[ -v country_map[$INPUT_LOWER] ]]; then
    COUNTRY_CODE=${country_map[$INPUT_LOWER]}
else
    COUNTRY_CODE=${country_input^^}
fi

URL="https://www.ipdeny.com/ipblocks/data/countries/${COUNTRY_CODE,,}.zone"
SETNAME="country_${COUNTRY_CODE,,}"

echo "[$(date '+%Y-%m-%d %H:%M:%S')] [INFO] Downloading IPs for country $COUNTRY_CODE..."
COUNTRY_IPS=$(curl -s "$URL")

if [ -z "$COUNTRY_IPS" ]; then
    echo "[$(date '+%Y-%m-%d %H:%M:%S')] [ERROR] Failed to fetch IP table for country '$COUNTRY_CODE'. Check if the code is correct."
    exit 1
fi

if ! ipset list "$SETNAME" &>/dev/null; then
    echo "[$(date '+%Y-%m-%d %H:%M:%S')] [INFO] Creating IPSET '$SETNAME'..."
    ipset create "$SETNAME" hash:net
fi

if ! iptables -C INPUT -m set --match-set "$SETNAME" src -j DROP &>/dev/null; then
    echo "[$(date '+%Y-%m-%d %H:%M:%S')] [INFO] Adding IPTABLES rules to IPSET '$SETNAME'..."
    iptables -I INPUT -m set --match-set "$SETNAME" src -j DROP
fi

echo "[$(date '+%Y-%m-%d %H:%M:%S')] [INFO] Adding IPs to IPSET '$SETNAME'..."
count=0
error_count=0
while IFS= read -r ip; do
    if [[ -n "$ip" && ! "$ip" =~ ^# ]]; then
        if ipset add "$SETNAME" "$ip" 2>/dev/null; then
            ((count++))
        else
            ((error_count++))
        fi
    fi
done <<< "$COUNTRY_IPS"

sudo netfilter-persistent save
echo "[$(date '+%Y-%m-%d %H:%M:%S')] [INFO] Task finished for IPSET $SETNAME. IPs blocked: $count, errors: $error_count"
